network:
  name: "localnet"
  cross_shard_tx_wait_time: 16 # The time to wait for account balances to properly updated when performing cross shard transfers
  gas:
    cost: 0.1 # Estimated gas cost that will be used for various transaction and funding calculations etc.
    limit: 53000 # Higher limit than regular txs (21000) - seems there are some issues occasionally when using a lower gas limit 
    price: 1

account:
  passphrase: ""
  remove_empty: true
  use_all_in_keystore: false
  
funding:
  account:
    name: "TestSuiteFundingAccount" # This name will be prefixed with the current network name
    address: ""
  minimum_funds: 10.0
  confirmation_wait_time: 16
  attempts: 10
  gas:
    cost: 0.0001
    limit: 53000
    price: 1
