network:
  name: "localnet"
  gas_cost: 0.1

account:
  passphrase: ""
  remove_empty: true
  use_all_in_keystore: false
  
funding:
  account:
    name: "TestSuiteFundingAccount" # This name will be prefixed with the current network name
    address: ""
  minimum_funds: 10.0
  confirmation_wait_time: 16
  attempts: 3
  gas_limit: 53_000
  gas_price: 1
